//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECA.Model
{
    using System;
    using System.Collections.Generic;
    
     using System.Runtime.Serialization;
    [DataContract(Name="Author",IsReference=true)] 
    public partial class Author
    {
    	
        public Author()
        {
    		
            this.Books = new HashSet<Book>();
        }
    
    	[DataMember(Name="AuthorId")]
        public string AuthorId { get; set; }
    	[DataMember(Name="AuthorName")]
        public string AuthorName { get; set; }
    
    [DataMember(Name="Books")]
        public virtual ICollection<Book> Books { get; set; }
    }
}
