//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECA.Model
{
    using System;
    using System.Collections.Generic;
    
     using System.Runtime.Serialization;
    [DataContract(Name="Genre",IsReference=true)] 
    public partial class Genre
    {
    	
        public Genre()
        {
    		
            this.Books = new HashSet<Book>();
        }
    
    	[DataMember(Name="GenreId")]
        public string GenreId { get; set; }
    	[DataMember(Name="GenreName")]
        public string GenreName { get; set; }
    
    [DataMember(Name="Books")]
        public virtual ICollection<Book> Books { get; set; }
    }
}
