//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECA.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ECAEntities : DbContext
    {
        public ECAEntities()
            : base("name=ECAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public IDbSet<Author> Authors { get; set; }
        public IDbSet<Book> Books { get; set; }
        public IDbSet<BookCategory> BookCategories { get; set; }
        public IDbSet<Genre> Genres { get; set; }
        public IDbSet<Cart> Carts { get; set; }
        public IDbSet<User> Users { get; set; }
        public IDbSet<webpages_Membership> webpages_Membership { get; set; }
        public IDbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public IDbSet<webpages_Roles> webpages_Roles { get; set; }
    }
}
