//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECA.Model
{
    using System;
    using System.Collections.Generic;
    
     using System.Runtime.Serialization;
    [DataContract(Name="webpages_Roles",IsReference=true)] 
    public partial class webpages_Roles
    {
    	
        public webpages_Roles()
        {
    		
            this.Users = new HashSet<User>();
        }
    
    	[DataMember(Name="RoleId")]
        public int RoleId { get; set; }
    	[DataMember(Name="RoleName")]
        public string RoleName { get; set; }
    
    [DataMember(Name="Users")]
        public virtual ICollection<User> Users { get; set; }
    }
}
