//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECA.Model
{
    using System;
    using System.Collections.Generic;
    
     using System.Runtime.Serialization;
    [DataContract(Name="webpages_Membership",IsReference=true)] 
    public partial class webpages_Membership
    {
    	[DataMember(Name="UserId")]
        public int UserId { get; set; }
    	[DataMember(Name="CreateDate")]
        public Nullable<System.DateTime> CreateDate { get; set; }
    	[DataMember(Name="ConfirmationToken")]
        public string ConfirmationToken { get; set; }
    	[DataMember(Name="IsConfirmed")]
        public Nullable<bool> IsConfirmed { get; set; }
    	[DataMember(Name="LastPasswordFailureDate")]
        public Nullable<System.DateTime> LastPasswordFailureDate { get; set; }
    	[DataMember(Name="PasswordFailuresSinceLastSuccess")]
        public int PasswordFailuresSinceLastSuccess { get; set; }
    	[DataMember(Name="Password")]
        public string Password { get; set; }
    	[DataMember(Name="PasswordChangedDate")]
        public Nullable<System.DateTime> PasswordChangedDate { get; set; }
    	[DataMember(Name="PasswordSalt")]
        public string PasswordSalt { get; set; }
    	[DataMember(Name="PasswordVerificationToken")]
        public string PasswordVerificationToken { get; set; }
    	[DataMember(Name="PasswordVerificationTokenExpirationDate")]
        public Nullable<System.DateTime> PasswordVerificationTokenExpirationDate { get; set; }
    }
}
