//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ECA.Model
{
    using System;
    using System.Collections.Generic;
    
     using System.Runtime.Serialization;
    [DataContract(Name="webpages_OAuthMembership",IsReference=true)] 
    public partial class webpages_OAuthMembership
    {
    	[DataMember(Name="Provider")]
        public string Provider { get; set; }
    	[DataMember(Name="ProviderUserId")]
        public string ProviderUserId { get; set; }
    	[DataMember(Name="UserId")]
        public int UserId { get; set; }
    }
}
